version: '3'
services:
  server:
    image: philippevallerand/gestion_inventaire_serveur
    container_name: gestion_inventaire_serveur
    depends_on:
      - postgres
    ports:
      - "8083:8081"
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5433/inventaire?useUnicode=true&characterEncoding=utf8&useSSL=false
        - spring.datasource.username=admin
        - spring.datasource.password=root
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: inventaire
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    command: -p 5433

  interface:
    image: philippevallerand/gestion_inventaire_interface
    container_name: gestion_inventaire_interface
    ports:
      - "8000:8000"
    links:
      - server
